apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: localstack
    app.kubernetes.io/version: {{ .Values.image.tag }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  - name: edge
    port: {{ .Values.service.edge.port }}
    targetPort: {{ .Values.endpoint.edge.port }}
  - name: web
    port: {{ .Values.service.web.port }}
    targetPort: {{ .Values.endpoint.web.port }}
  type: {{ .Values.service.web.type }}
  selector:
    app.kubernetes.io/name: localstack
    app.kubernetes.io/version: {{ .Values.image.tag }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
